sonar.organization=MatthieuFranques
sonar.projectKey=smartapply-rag
sonar.projectName=SmartApply RAG
sonar.sources=app
sonar.tests=tests
sonar.exclusions=**/__pycache__/**,**/venv/**,**/.env,**/data/**
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11
