sonar.organization=matthieufranques
sonar.projectKey=MatthieuFranques_SmartApply
sonar.projectName=SmartApply

sonar.sources=src/SmartApplyPipeline/app,src/SmartApplyGmail/app,src/SmartApplyRag/app,src/SmartApplyFront/src
sonar.tests=src/SmartApplyPipeline/tests,src/SmartApplyGmail/tests,src/SmartApplyRag/tests

sonar.exclusions=**/__pycache__/**,**/venv/**,**/.env,**/data/**,**/node_modules/**,**/*.spec.ts
sonar.coverage.exclusions=src/SmartApplyFront/**

sonar.continuousintegration.disableAutoscan=true

sonar.python.coverage.reportPaths=src/SmartApplyPipeline/coverage.xml,src/SmartApplyGmail/coverage.xml,src/SmartApplyRag/coverage.xml
sonar.python.version=3.11
