sonar.projectKey=${SonarProjectKey}
sonar.organization=${SonarOrganization}

sonar.projectName=SmartApply Backend
sonar.sources=.
sonar.exclusions=**/tests/**,**/__pycache__/**,**/venv/**,**/.env

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11